name: untitled
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  carousel_slider_plus: ^7.1.2
  video_player: ^2.11.1
  path_provider: ^2.1.0
  intl: ^0.20.3
  table_calendar: ^3.2.0
  webview_flutter: ^4.14.0
  url_launcher: ^6.3.2
  youtube_player_iframe: ^6.0.2
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.3.0
  font_awesome_flutter: ^11.0.0
  chewie: ^1.7.1
  fluttertoast: ^9.0.0
  dio: ^5.11.0
  get: ^4.7.3
  shared_preferences: ^2.5.5
  file_picker: ^10.3.10
  image_picker: ^1.0.7
  shimmer: ^3.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/Suwidhaa.png"
  adaptive_icon_background: "#FFFFFF" # Yahan apna color code dein
  adaptive_icon_foreground: "assets/logo/Suwidhaa.png"

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/logo/

